version: 0.0
os: linux

files:
  - source: ./
    destination: /home/ec2-user/

permissions:
  - object: /home/ec2-user/
    owner: ec2-user

hooks:
  ApplicationStop:
    - location: /bin/stop.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: /bin/start.sh
      timeout: 300
      runas: ec2-user
